; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags = 
	-I include
lib_ldf_mode = deep+
lib_deps = 
	marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
	miguelbalboa/MFRC522 @ ^1.4.11          ; Nome completo do autor
	knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7.0.4          ; Versão mais recente e estável
	adafruit/Adafruit PN532 @ ^1.3.4
    adafruit/Adafruit BusIO @ ^1.16.1       ; <--- ADICIONE ESTA LINHA
    
upload_protocol = espota
upload_port = 192.168.0.115
